config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
resources :flats
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all

    if params[:query].present?
      @flats = @flats.where("name LIKE ? COLLATE NOCASE", "%#{params[:query]}%")
    end



  end
   def new
    @flat = Flat.new
  end

  def show
    @flat = Flat.find_by(params[:id])
  end



  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to flats_path, notice: "Flat was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to flats_path, notice: 'Flat was successfully deleted.'
  end

  private
  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">Airbnb </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="<%= @flats_path %>">Home</a>
        </li>
      </ul>

       <%= form_with url: flats_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search for"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
    </form>

      <a href="<%= new_flat_path %>" class="btn btn-primary ml-3">Create New Listing</a>
    </div>
  </div>
</nav>


<div class="container mt-3">
  <div class="row row-cols-1 row-cols-lg-3 row-cols-md-2 g-4">
    <% @flats.each do |flat| %>
      <div class="col">
        <div class="card h-100">
          <img src="<%= flat.image %>" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= flat.name %></h5>
            <p class="card-text"><%= flat.description %></p>
            <div class="d-flex justify-content-between">
              <p class="card-text"><%= flat.price_per_night %>$</p>
              <p class="card-text"><%= flat.number_of_guests %> Guests</p>

            </div>
              <%= link_to 'Delete', flat_path(flat), method: :delete, data: { "turbo-method": :delete }, class: 'btn btn-danger' %>

            <a href="<%= flat_path(flat) %>" class="btn btn-primary" style="text-decoration: none;">View Details</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
   <%= f.input :address %>
   <%= f.input :description %>
   <%= f.input :price_per_night %>
   <%= f.input :number_of_guests %>
   <%= f.input :image %>

  <%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">Airbnb 🛀🏼</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="<%= @flats_path %>">Home</a>
        </li>
      </ul>

       <%= form_with url: flats_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search for"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
    </form>

      <a href="<%= new_flat_path %>" class="btn btn-primary ml-3">Create New Listing</a>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="mb-4">
        <img src="<%= @flat.image %>" class="card-img-top" alt="Flat Image">
      </div>
    </div>
    <div class="col-lg-6">
      <div>
        <div>
          <h5><%= @flat.name %></h5>
          <p class="card-text"><%= @flat.description %></p>
          <div class="d-flex justify-content-between">
            <p><%= @flat.price_per_night %>$</p>
            <p><%= @flat.number_of_guests %> Guests</p>
          </div>
          <a href="<%= flats_path %>" class="btn btn-primary" style="text-decoration: none;">Back to 🛀🏻</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>